version: '3.8'

services:
  app:
    container_name: golang_container
    build: .
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - fullstack
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512M
      
  postgresdb:
    container_name: postgres_container
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fullstack
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512M

volumes:
  pgdata:

networks:
  fullstack:
    driver: bridge 